"""
Django settings for subsocks_controller project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b%a3cgbdck1uw2_q9y)wf0z-hss=rw7!l9(n_#*(e+c*-)(ao9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'subsocks_controller.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'subsocks_controller.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = os.path.join(BASE_DIR, "static")

SIMPLEUI_HOME_INFO = False # 隐藏右侧simple广告链接
SIMPLEUI_ANALYSIS = False  # 隐藏右侧Simple使用分析

SIMPLEUI_CONFIG = {
    'system_keep': False,
    'dynamic': True,
    'menus': [
        {
            'app': 'myapp',
            'name': '客户接入机制',
            'icon': 'fa fa-mobile',
            'models': [{
                'name': '客户端表',
                'icon': 'fa fa-users',
                'url': 'myapp/clienttable'
            },{
                'name': 'Zitadel身份表',
                'icon': 'fa fa-refresh',
                'url': 'myapp/zitadeltable',
            },{
                'name': '接入点表',
                'icon': 'fa fa-cloud-upload',
                'url': 'myapp/accesstable'
            },{
                'name': '服务表',
                'icon': 'fa fa-align-justify',
                'url': 'myapp/servicetable'
            },{
                'name': '证书信息表',
                'icon': 'fa fa-book',
                'url': 'myapp/certtable'
            }]
        },{
            'app': 'myapp',
            'name': '服务控制策略',
            'icon': 'fa fa-sitemap',
            'models': [{
                'name': '绑定策略',
                'icon': 'fa fa-server',
                'url': 'myapp/bindtable'
            },{
                'name': '拨入策略',
                'icon': 'fa fa-mobile',
                'url': 'myapp/dialtable'
            }]
        },{
            'app': 'auth',
            'name': '认证和授权',
            'icon': 'fas fa-shield-alt',
            'models': [{
                'name': '用户',
                'icon': 'far fa-user',
                'url': 'auth/user/'
            }, {
                'name': '组',
                'icon': 'fas fa-users-cog',
                'url': 'auth/group/',
            }]
        },

    ]
}
