# Generated by Django 5.2.8 on 2025-11-21 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='证书信息别名')),
                ('ca_cert', models.TextField(verbose_name='证书')),
                ('ca_secret', models.TextField(verbose_name='密钥')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '证书信息表',
                'verbose_name_plural': '证书信息表',
            },
        ),
        migrations.CreateModel(
            name='ServiceTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='服务别名')),
                ('addr', models.CharField(max_length=255, verbose_name='地址 (host, port)')),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], max_length=10, verbose_name='服务类型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '服务表',
                'verbose_name_plural': '服务表',
            },
        ),
        migrations.CreateModel(
            name='AccessTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='接入点别名')),
                ('addr', models.CharField(max_length=255, verbose_name='地址 (host:port)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ca_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.certtable', verbose_name='证书信息')),
            ],
            options={
                'verbose_name': '接入点表',
                'verbose_name_plural': '接入点表',
            },
        ),
        migrations.CreateModel(
            name='ClientTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='客户端别名')),
                ('addr', models.CharField(max_length=255, verbose_name='地址 (host:port)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('access_point', models.ManyToManyField(to='myapp.accesstable', verbose_name='接入点列表')),
            ],
            options={
                'verbose_name': '客户端表',
                'verbose_name_plural': '客户端表',
            },
        ),
    ]
