# Generated by Django 5.2.8 on 2025-11-21 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_certtable_servicetable_accesstable_clienttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accesstable', verbose_name='接入点')),
                ('service', models.ManyToManyField(to='myapp.servicetable', verbose_name='服务列表')),
            ],
            options={
                'verbose_name': '服务绑定策略',
                'verbose_name_plural': '服务绑定策略',
            },
        ),
        migrations.CreateModel(
            name='DialTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.clienttable', verbose_name='客户端')),
                ('service', models.ManyToManyField(to='myapp.servicetable', verbose_name='服务列表')),
            ],
            options={
                'verbose_name': '服务接入策略',
                'verbose_name_plural': '服务接入策略',
            },
        ),
    ]
