# Generated by Django 5.2.8 on 2025-11-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bindtable_dialtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttable',
            name='addr',
        ),
        migrations.AddField(
            model_name='clienttable',
            name='service',
            field=models.ManyToManyField(to='myapp.servicetable', verbose_name='服务访问列表'),
        ),
    ]
