# Generated by Django 5.2.8 on 2025-11-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_clienttable_addr_clienttable_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='name',
            field=models.CharField(max_length=100, verbose_name='客户端别名'),
        ),
    ]
