# Generated by Django 5.2.8 on 2025-12-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_clienttable_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZitadelTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Client', 'Client'), ('Access', 'Access')], max_length=10, verbose_name='身份类型')),
                ('client_id', models.CharField(max_length=100, verbose_name='用户名')),
                ('client_secret', models.CharField(max_length=100, verbose_name='密码')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='用户ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Zitadel表',
                'verbose_name_plural': 'Zitadel表',
            },
        ),
    ]
